Document: abcmidi
Title: Debian abcmidi Manual
Author: <insert document author here>
Abstract: This manual describes what abcmidi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/abcmidi/abcmidi.sgml.gz

Format: postscript
Files: /usr/share/doc/abcmidi/abcmidi.ps.gz

Format: text
Files: /usr/share/doc/abcmidi/abcmidi.text.gz

Format: HTML
Index: /usr/share/doc/abcmidi/html/index.html
Files: /usr/share/doc/abcmidi/html/*.html
